In [1]:
import pandas as pd
import os

In [2]:
os.getcwd()

'C:\\Users\\ADMIN\\OneDrive\\Desktop\\WORKSHOP'

In [3]:
df=pd.read_csv('dataset/retail_sales_customer_analytics_dataset.csv')

In [4]:
df

,Order_ID,Customer_ID,Customer_Name,Branch,Product,Product_Category,Order_Date,Quantity,Unit_Price,Discount_Percent,...,Net_Sales,Profit,Payment_Method,Customer_Type,Sales_Channel,Order_Status,Return_Status,Customer_Feedback,Rating,Year
0,ORD10000,CUST1125,Mary Wanjiku,Thika,Desktop,Computers,2026-10-17,2.0,1500.0,-5.0,...,3150.0,-12850.0,NaN,NaN,Physical Store,Completed,Yes,Neutral,2.0,NaN
1,ORD10001,CUST1359,David Kariuki,Eldoret,Printer,Office Equipment,2026-09-09,1.0,25000.0,-5.0,...,26250.0,-33750.0,NaN,Institution,Physical Store,Cancelled,no,Dissatisfied,3.0,2025.0
2,ORD10002,CUST1049,Peter Otieno,Kisumu,UPS,Networking,2025-08-09,20.0,5000.0,0.0,...,100000.0,-260000.0,Cash,NaN,Physical Store,NaN,Yes,Dissatisfied,7.0,NaN
3,ORD10003,CUST1023,NaN,Nakuru,Router,Computers,2026-09-26,20.0,25000.0,-5.0,...,525000.0,509000.0,Card,Individual,NaN,Pending,no,Dissatisfied,2.0,2026.0
4,ORD10004,CUST1331,John Mwangi,Thika,Projector,Accessories,2025-12-30,5.0,50000.0,-5.0,...,262500.0,-37500.0,Card,NaN,NaN,Pending,NaN,Neutral,NaN,2026.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,ORD11410,CUST1119,David Kariuki,Nyeri,Projector,Computers,2026-08-12,10.0,50000.0,15.0,...,425000.0,395000.0,Mobile Money,Business,Physical Store,Pending,no,NaN,3.0,2025.0
1996,ORD11515,CUST1230,Amina Hassan,Westlands,UPS,Accessories,2026-07-21,5.0,-500.0,NaN,...,NaN,NaN,Bank Transfer,Institution,Online,Pending,YES,Satisfied,5.0,2026.0
1997,ORD10809,CUST1080,NaN,Kisumu,Laptop,Accessories,2026-06-05,20.0,25000.0,NaN,...,NaN,NaN,Card,Individual,NaN,Pending,no,Neutral,3.0,2025.0
1998,ORD10830,CUST1304,Peter Otieno,Thika,Desktop,Accessories,2025-11-02,5.0,85000.0,10.0,...,382500.0,207500.0,Cash,Institution,NaN,Completed,No,NaN,1.0,2025.0
1999,ORD10859,CUST1318,Peter Otieno,Eldoret,Mouse,Computers,2026-06-18,1.0,25000.0,10.0,...,22500.0,14500.0,Mobile Money,Individual,Online,NaN,no,Dissatisfied,4.0,2026.0

In [5]:
df.columns

Index(['Order_ID', 'Customer_ID', 'Customer_Name', 'Branch', 'Product',
       'Product_Category', 'Order_Date', 'Quantity', 'Unit_Price',
       'Discount_Percent', 'Gross_Revenue', 'Cost', 'Net_Sales', 'Profit',
       'Payment_Method', 'Customer_Type', 'Sales_Channel', 'Order_Status',
       'Return_Status', 'Customer_Feedback', 'Rating', 'Year'],
      dtype='str')

In [6]:
list(df.columns)

['Order_ID',
 'Customer_ID',
 'Customer_Name',
 'Branch',
 'Product',
 'Product_Category',
 'Order_Date',
 'Quantity',
 'Unit_Price',
 'Discount_Percent',
 'Gross_Revenue',
 'Cost',
 'Net_Sales',
 'Profit',
 'Payment_Method',
 'Customer_Type',
 'Sales_Channel',
 'Order_Status',
 'Return_Status',
 'Customer_Feedback',
 'Rating',
 'Year']

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Order_ID           2000 non-null   str
 1   Customer_ID        2000 non-null   str
 2   Customer_Name      1664 non-null   str
 3   Branch             2000 non-null   str
 4   Product            2000 non-null   str
 5   Product_Category   2000 non-null   str
 6   Order_Date         2000 non-null   str
 7   Quantity           1719 non-null   float64
 8   Unit_Price         1723 non-null   float64
 9   Discount_Percent   1680 non-null   float64
 10  Gross_Revenue      1480 non-null   float64
 11  Cost               1719 non-null   float64
 12  Net_Sales          1245 non-null   float64
 13  Profit             1245 non-null   float64
 14  Payment_Method     1613 non-null   str
 15  Customer_Type      1484 non-null   str
 16  Sales_Channel      1507 non-null   str
 17  Order_Status       1475 non-null   str
 18  Return_Status      1601 non-null   str
 19  Customer_Feedback  1518 non-null   str
 20  Rating             1719 non-null   float64
 21  Year               1346 non-null   float64
dtypes: float64(9), str(13)
memory usage: 343.9 KB

In [8]:
df.describe()

,Quantity,Unit_Price,Discount_Percent,Gross_Revenue,Cost,Net_Sales,Profit,Rating,Year
count,1719.000000,1723.000000,1680.000000,1.480000e+03,1.719000e+03,1.245000e+03,1.245000e+03,1719.000000,1346.000000
mean,5.556137,25113.464887,5.000000,1.373159e+05,1.120828e+05,1.303379e+05,2.291410e+04,3.567190,2025.478455
std,6.824267,29442.758966,7.068962,3.036701e+05,2.231529e+05,2.837743e+05,2.847705e+05,1.954367,0.499721
min,-2.000000,-500.000000,-5.000000,-1.700000e+05,-1.200000e+05,-1.785000e+05,-1.210500e+06,1.000000,2025.000000
25%,1.000000,1500.000000,0.000000,6.250000e+02,4.000000e+03,9.500000e+02,-6.000000e+04,2.000000,2025.000000
50%,3.000000,12000.000000,5.000000,2.500000e+04,3.500000e+04,2.500000e+04,-1.425000e+03,3.000000,2025.000000
75%,10.000000,50000.000000,10.000000,1.250000e+05,1.200000e+05,1.260000e+05,6.900000e+04,5.000000,2026.000000
max,20.000000,85000.000000,15.000000,1.700000e+06,1.200000e+06,1.785000e+06,1.684000e+06,7.000000,2026.000000

In [9]:
df.shape

(2000, 22)

In [10]:
df.isna().values.any()

np.True_

In [11]:
df.isna().sum()

Order_ID               0
Customer_ID            0
Customer_Name        336
Branch                 0
Product                0
Product_Category       0
Order_Date             0
Quantity             281
Unit_Price           277
Discount_Percent     320
Gross_Revenue        520
Cost                 281
Net_Sales            755
Profit               755
Payment_Method       387
Customer_Type        516
Sales_Channel        493
Order_Status         525
Return_Status        399
Customer_Feedback    482
Rating               281
Year                 654
dtype: int64

In [12]:
df.isna().sum().sum()

np.int64(7262)

In [14]:
df['Net_Sales'].isna().sum()

np.int64(755)

In [15]:
df[df['Net_Sales'].isna()]

,Order_ID,Customer_ID,Customer_Name,Branch,Product,Product_Category,Order_Date,Quantity,Unit_Price,Discount_Percent,...,Net_Sales,Profit,Payment_Method,Customer_Type,Sales_Channel,Order_Status,Return_Status,Customer_Feedback,Rating,Year
6,ORD10006,CUST1185,Mary Wanjiku,Thika,Projector,Office Equipment,2026-07-29,10.0,NaN,NaN,...,NaN,NaN,Cash,Individual,Physical Store,Cancelled,No,NaN,5.0,2025.0
7,ORD10007,CUST1128,David Kariuki,Nairobi CBD,Desktop,Networking,2026-01-30,NaN,-500.0,NaN,...,NaN,NaN,Mobile Money,Individual,Phone,NaN,No,NaN,1.0,NaN
9,ORD10009,CUST1043,NaN,Nyeri,Desktop,Accessories,2025-09-03,1.0,25000.0,NaN,...,NaN,NaN,Card,NaN,Online,Pending,NaN,NaN,2.0,NaN
10,ORD10010,CUST1191,Amina Hassan,Nyeri,Desktop,Accessories,2025-07-25,10.0,NaN,-5.0,...,NaN,NaN,Card,Individual,Phone,Completed,NaN,Neutral,5.0,2025.0
17,ORD10017,CUST1051,John Mwangi,Nakuru,Projector,Networking,2025-03-16,1.0,-500.0,NaN,...,NaN,NaN,Card,Institution,Physical Store,Cancelled,YES,Dissatisfied,2.0,2026.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1989,ORD10849,CUST1116,David Kariuki,Mombasa,UPS,Networking,2026-03-29,10.0,25000.0,NaN,...,NaN,NaN,NaN,Institution,Physical Store,Cancelled,NaN,Dissatisfied,3.0,NaN
1990,ORD11594,CUST1339,NaN,Kisumu,Printer,Computers,2025-10-20,NaN,85000.0,15.0,...,NaN,NaN,Bank Transfer,Individual,NaN,Cancelled,Yes,Satisfied,2.0,NaN
1992,ORD11225,CUST1033,Amina Hassan,Eldoret,Laptop,Computers,2025-10-19,-2.0,50000.0,NaN,...,NaN,NaN,NaN,Individual,Physical Store,Completed,YES,NaN,4.0,NaN
1996,ORD11515,CUST1230,Amina Hassan,Westlands,UPS,Accessories,2026-07-21,5.0,-500.0,NaN,...,NaN,NaN,Bank Transfer,Institution,Online,Pending,YES,Satisfied,5.0,2026.0
1997,ORD10809,CUST1080,NaN,Kisumu,Laptop,Accessories,2026-06-05,20.0,25000.0,NaN,...,NaN,NaN,Card,Individual,NaN,Pending,no,Neutral,3.0,2025.0

In [18]:
Net_Sale_Branch_Product=df.loc[
    df['Net_Sales'].isna(),
    ['Branch','Product','Product','Product_Category','Order_Date']
    ]

In [19]:
Net_Sale_Branch_Product.to_csv('dataset/Net_Sales_Branch_Product.csv',index=False)

In [21]:
os.path.exists('dataset.Net_Sales_Branch_Product.csv')

False

In [22]:
df[
    df['Customer_Name'].isnull() &
    df['Discount_Percent'].isnull()
    ]

,Order_ID,Customer_ID,Customer_Name,Branch,Product,Product_Category,Order_Date,Quantity,Unit_Price,Discount_Percent,...,Net_Sales,Profit,Payment_Method,Customer_Type,Sales_Channel,Order_Status,Return_Status,Customer_Feedback,Rating,Year
9,ORD10009,CUST1043,NaN,Nyeri,Desktop,Accessories,2025-09-03,1.0,25000.0,NaN,...,NaN,NaN,Card,NaN,Online,Pending,NaN,NaN,2.0,NaN
84,ORD10084,CUST1283,NaN,Nairobi CBD,External Drive,Accessories,2026-09-22,NaN,-500.0,NaN,...,NaN,NaN,Mobile Money,NaN,Online,Completed,no,Satisfied,7.0,2026.0
156,ORD10156,CUST1346,NaN,Eldoret,Keyboard,Office Equipment,2025-12-30,3.0,1500.0,NaN,...,NaN,NaN,Cash,Individual,Physical Store,Pending,No,Neutral,4.0,2026.0
169,ORD10169,CUST1444,NaN,Westlands,External Drive,Networking,2026-04-11,-2.0,85000.0,NaN,...,NaN,NaN,Cash,NaN,Online,NaN,No,NaN,3.0,2026.0
195,ORD10195,CUST1360,NaN,Kisumu,UPS,Accessories,2026-08-30,20.0,85000.0,NaN,...,NaN,NaN,NaN,Business,NaN,Pending,No,NaN,1.0,2025.0
242,ORD10242,CUST1355,NaN,Kisumu,Desktop,Networking,2026-11-20,3.0,12000.0,NaN,...,NaN,NaN,NaN,NaN,NaN,Pending,no,Satisfied,5.0,2025.0
250,ORD10250,CUST1003,NaN,Westlands,Printer,Accessories,2025-03-26,2.0,12000.0,NaN,...,NaN,NaN,Bank Transfer,Individual,Online,NaN,Yes,Neutral,1.0,2026.0
272,ORD10272,CUST1314,NaN,Nairobi CBD,Monitor,Office Equipment,2026-06-05,NaN,85000.0,NaN,...,NaN,NaN,Cash,Individual,Online,NaN,NaN,NaN,1.0,2025.0
291,ORD10291,CUST1069,NaN,Thika,UPS,Office Equipment,2026-05-03,-2.0,50000.0,NaN,...,NaN,NaN,NaN,NaN,Phone,Pending,no,Neutral,7.0,2025.0
302,ORD10302,CUST1165,NaN,Nyeri,Router,Accessories,2026-05-17,5.0,12000.0,NaN,...,NaN,NaN,Cash,Business,NaN,Pending,YES,Dissatisfied,4.0,2025.0
305,ORD10305,CUST1319,NaN,Mombasa,Laptop,Networking,2026-08-08,NaN,-500.0,NaN,...,NaN,NaN,Card,Individual,Physical Store,Cancelled,no,Satisfied,4.0,NaN
322,ORD10322,CUST1313,NaN,Nakuru,Mouse,Accessories,2025-05-21,2.0,NaN,NaN,...,NaN,NaN,NaN,Business,NaN,Pending,NaN,Dissatisfied,4.0,NaN
375,ORD10375,CUST1124,NaN,Thika,Laptop,Accessories,2026-05-16,1.0,-500.0,NaN,...,NaN,NaN,Cash,Institution,Physical Store,NaN,NaN,Neutral,7.0,NaN
400,ORD10400,CUST1110,NaN,Nyeri,Mouse,Office Equipment,2025-12-26,10.0,-500.0,NaN,...,NaN,NaN,Mobile Money,Business,NaN,NaN,No,Satisfied,2.0,2025.0
473,ORD10473,CUST1248,NaN,Nyeri,Monitor,Computers,2026-03-03,3.0,12000.0,NaN,...,NaN,NaN,Card,NaN,NaN,Completed,No,Dissatisfied,1.0,NaN
530,ORD10530,CUST1218,NaN,Nyeri,Router,Accessories,2026-08-30,5.0,25000.0,NaN,...,NaN,NaN,Card,Business,NaN,Cancelled,NaN,Neutral,3.0,2026.0
552,ORD10552,CUST1226,NaN,Nyeri,Router,Accessories,2025-11-08,-2.0,12000.0,NaN,...,NaN,NaN,Card,Business,Online,Completed,YES,Satisfied,NaN,2025.0
606,ORD10606,CUST1020,NaN,Eldoret,Printer,Accessories,2025-12-14,10.0,85000.0,NaN,...,NaN,NaN,NaN,Individual,Online,NaN,Yes,Satisfied,2.0,2026.0
633,ORD10633,CUST1215,NaN,Eldoret,Keyboard,Networking,2025-04-16,10.0,5000.0,NaN,...,NaN,NaN,Card,Business,Physical Store,NaN,no,Satisfied,3.0,2026.0
702,ORD10702,CUST1194,NaN,Nakuru,Keyboard,Office Equipment,2025-02-09,NaN,50000.0,NaN,...,NaN,NaN,NaN,Business,Phone,Cancelled,YES,NaN,4.0,NaN
745,ORD10745,CUST1182,NaN,Nairobi CBD,Projector,Office Equipment,2025-11-29,10.0,1500.0,NaN,...,NaN,NaN,Card,Business,Physical Store,Completed,No,Neutral,NaN,2026.0
768,ORD10768,CUST1163,NaN,Westlands,Printer,Office Equipment,2026-05-04,-2.0,5000.0,NaN,...,NaN,NaN,Cash,NaN,Physical Store,NaN,No,Satisfied,5.0,NaN
789,ORD10789,CUST1379,NaN,Thika,Keyboard,Computers,2026-03-06,3.0,12000.0,NaN,...,NaN,NaN,Card,Individual,NaN,Cancelled,YES,NaN,NaN,2026.0
828,ORD10828,CUST1189,NaN,Nairobi CBD,Printer,Computers,2025-02-23,NaN,12000.0,NaN,...,NaN,NaN,Bank Transfer,Business,Online,Pending,Yes,Neutral,4.0,2025.0
879,ORD10879,CUST1146,NaN,Nakuru,Desktop,Computers,2025-06-19,-2.0,-500.0,NaN,...,NaN,NaN,Cash,Individual,Physical Store,Completed,YES,Satisfied,3.0,2026.0
916,ORD10916,CUST1012,NaN,Nakuru,Desktop,Office Equipment,2025-10-25,5.0,NaN,NaN,...,NaN,NaN,Cash,NaN,Phone,Pending,no,Satisfied,4.0,2026.0
925,ORD10925,CUST1071,NaN,Mombasa,Mouse,Accessories,2026-10-16,3.0,-500.0,NaN,...,NaN,NaN,Card,Individual,Online,NaN,YES,NaN,4.0,2026.0
948,ORD10948,CUST1444,NaN,Mombasa,UPS,Computers,2026-07-03,NaN,1500.0,NaN,...,NaN,NaN,Bank Transfer,Business,Phone,Completed,No,NaN,5.0,NaN
1001,ORD11001,CUST1208,NaN,Nairobi CBD,Keyboard,Computers,2025-02-07,10.0,12000.0,NaN,...,NaN,NaN,Mobile Money,Business,NaN,NaN,no,NaN,7.0,NaN
1040,ORD11040,CUST1309,NaN,Thika,External Drive,Computers,2026-01-28,2.0,-500.0,NaN,...,NaN,NaN,Mobile Money,Institution,Online,Cancelled,NaN,Dissatisfied,4.0,2025.0
1070,ORD11070,CUST1415,NaN,Kisumu,External Drive,Computers,2026-06-13,1.0,1500.0,NaN,...,NaN,NaN,Card,Individual,Physical Store,Pending,Yes,NaN,1.0,2025.0
1117,ORD11117,CUST1163,NaN,Nakuru,Desktop,Computers,2025-10-23,1.0,25000.0,NaN,...,NaN,NaN,Bank Transfer,Institution,NaN,Cancelled,No,Dissatisfied,3.0,2026.0
1122,ORD11122,CUST1338,NaN,Nyeri,UPS,Computers,2026-06-17,2.0,-500.0,NaN,...,NaN,NaN,Mobile Money,Individual,Phone,NaN,No,Dissatisfied,4.0,2025.0
1133,ORD11133,CUST1406,NaN,Thika,External Drive,Accessories,2025-04-29,NaN,5000.0,NaN,...,NaN,NaN,Mobile Money,Individual,Online,Completed,Yes,Dissatisfied,3.0,2025.0
1179,ORD11179,CUST1090,NaN,Nairobi CBD,UPS,Accessories,2025-12-21,20.0,12000.0,NaN,...,NaN,NaN,NaN,NaN,Online,Pending,No,Dissatisfied,5.0,2026.0
1191,ORD11191,CUST1290,NaN,Nyeri,Mouse,Computers,2026-03-17,NaN,-500.0,NaN,...,NaN,NaN,NaN,NaN,Online,Completed,No,NaN,4.0,2026.0
1255,ORD11255,CUST1364,NaN,Kisumu,Projector,Networking,2026-07-03,5.0,85000.0,NaN,...,NaN,NaN,Card,Business,Phone,Cancelled,YES,Neutral,NaN,2026.0
1381,ORD11381,CUST1134,NaN,Eldoret,Laptop,Networking,2026-08-19,5.0,-500.0,NaN,...,NaN,NaN,Bank Transfer,NaN,Physical Store,Pending,No,NaN,5.0,NaN
1400,ORD11400,CUST1207,NaN,Nairobi CBD,Printer,Office Equipment,2025-01-10,3.0,50000.0,NaN,...,NaN,NaN,Bank Transfer,Individual,Online,Pending,No,NaN,3.0,2025.0
1454,ORD11454,CUST1196,NaN,Westlands,Printer,Networking,2025-10-25,2.0,NaN,NaN,...,NaN,NaN,NaN,Institution,NaN,Pending,no,Dissatisfied,4.0,2025.0
1512,ORD11512,CUST1302,NaN,Nakuru,UPS,Computers,2026-07-06,3.0,50000.0,NaN,...,NaN,NaN,Bank Transfer,Individual,Phone,Cancelled,NaN,Satisfied,1.0,2026.0
1524,ORD11524,CUST1411,NaN,Westlands,Router,Computers,2026-11-17,1.0,12000.0,NaN,...,NaN,NaN,Cash,Business,NaN,Pending,YES,Neutral,4.0,NaN
1527,ORD11527,CUST1221,NaN,Thika,Mouse,Computers,2025-12-06,1.0,NaN,NaN,...,NaN,NaN,Bank Transfer,Institution,Phone,Pending,No,Dissatisfied,2.0,NaN
1618,ORD11618,CUST1421,NaN,Westlands,UPS,Accessories,2025-09-23,NaN,1500.0,NaN,...,NaN,NaN,Mobile Money,Individual,Physical Store,NaN,YES,Dissatisfied,7.0,2026.0
1629,ORD11629,CUST1316,NaN,Westlands,Keyboard,Accessories,2026-03-29,10.0,85000.0,NaN,...,NaN,NaN,Cash,Institution,Phone,Pending,Yes,Satisfied,7.0,2025.0
1634,ORD11634,CUST1370,NaN,Eldoret,Printer,Office Equipment,2025-07-21,2.0,NaN,NaN,...,NaN,NaN,Cash,Business,Physical Store,NaN,No,NaN,5.0,2025.0
1646,ORD11646,CUST1373,NaN,Mombasa,UPS,Office Equipment,2026-05-07,20.0,-500.0,NaN,...,NaN,NaN,Mobile Money,NaN,Physical Store,Pending,No,Neutral,1.0,2026.0
1735,ORD11735,CUST1015,NaN,Nairobi CBD,Desktop,Office Equipment,2025-03-21,-2.0,85000.0,NaN,...,NaN,NaN,Cash,NaN,NaN,Pending,NaN,Satisfied,4.0,NaN
1782,ORD11782,CUST1121,NaN,Westlands,Monitor,Networking,2025-05-14,20.0,5000.0,NaN,...,NaN,NaN,NaN,NaN,NaN,Cancelled,no,NaN,4.0,2025.0
1828,ORD11828,CUST1207,NaN,Kisumu,Router,Office Equipment,2025-02-07,2.0,1500.0,NaN,...,NaN,NaN,Cash,Business,Phone,Cancelled,no,Satisfied,4.0,2026.0
1855,ORD11855,CUST1129,NaN,Westlands,Mouse,Accessories,2026-07-18,10.0,12000.0,NaN,...,NaN,NaN,Bank Transfer,NaN,Online,NaN,YES,Satisfied,2.0,NaN
1904,ORD11904,CUST1315,NaN,Eldoret,Projector,Computers,2025-11-05,1.0,85000.0,NaN,...,NaN,NaN,Mobile Money,Institution,Physical Store,Completed,No,Dissatisfied,5.0,2026.0
1911,ORD11911,CUST1265,NaN,Nyeri,UPS,Office Equipment,2026-03-10,-2.0,NaN,NaN,...,NaN,NaN,Bank Transfer,Institution,Phone,Pending,YES,Dissatisfied,4.0,2026.0
1916,ORD11916,CUST1325,NaN,Thika,Router,Networking,2026-10-29,-2.0,5000.0,NaN,...,NaN,NaN,Bank Transfer,Institution,NaN,Cancelled,Yes,Satisfied,2.0,NaN
1933,ORD11933,CUST1363,NaN,Westlands,External Drive,Computers,2025-09-03,NaN,12000.0,NaN,...,NaN,NaN,Mobile Money,Institution,Phone,Completed,NaN,Neutral,5.0,2026.0
1961,ORD11961,CUST1364,NaN,Kisumu,Desktop,Networking,2026-03-07,3.0,-500.0,NaN,...,NaN,NaN,Card,Institution,Phone,Pending,NaN,NaN,4.0,NaN
1971,ORD11971,CUST1184,NaN,Nakuru,Projector,Accessories,2026-02-26,1.0,12000.0,NaN,...,NaN,NaN,NaN,Institution,NaN,Completed,no,Dissatisfied,4.0,NaN
1997,ORD10809,CUST1080,NaN,Kisumu,Laptop,Accessories,2026-06-05,20.0,25000.0,NaN,...,NaN,NaN,Card,Individual,NaN,Pending,no,Neutral,3.0,2025.0

In [26]:
df.loc[
    df['Customer_Name'].isnull() |
    df['Discount_Percent'].isnull(),
    ['Customer_Name','Customer_ID','Order_ID','Product','Branch']
    ]

      Customer_Name Customer_ID  Order_ID    Product       Branch
3               NaN    CUST1023  ORD10003     Router       Nakuru
6      Mary Wanjiku    CUST1185  ORD10006  Projector        Thika
7     David Kariuki    CUST1128  ORD10007    Desktop  Nairobi CBD
8               NaN    CUST1430  ORD10008    Monitor       Nakuru
9               NaN    CUST1043  ORD10009    Desktop        Nyeri
...             ...         ...       ...        ...          ...
1989  David Kariuki    CUST1116  ORD10849        UPS      Mombasa
1990            NaN    CUST1339  ORD11594    Printer       Kisumu
1992   Amina Hassan    CUST1033  ORD11225     Laptop      Eldoret
1996   Amina Hassan    CUST1230  ORD11515        UPS    Westlands
1997            NaN    CUST1080  ORD10809     Laptop       Kisumu

[598 rows x 5 columns]

In [27]:
df[
    df.isnull().all(axis=1)
    ]

Empty DataFrame
Columns: [Order_ID, Customer_ID, Customer_Name, Branch, Product, Product_Category, Order_Date, Quantity, Unit_Price, Discount_Percent, Gross_Revenue, Cost, Net_Sales, Profit, Payment_Method, Customer_Type, Sales_Channel, Order_Status, Return_Status, Customer_Feedback, Rating, Year]
Index: []

[0 rows x 22 columns]

In [29]:
df.isnull().all(axis=1).sum()

np.int64(0)

In [30]:
df[
    df.isnull().any(axis=1)
    ]

,Order_ID,Customer_ID,Customer_Name,Branch,Product,Product_Category,Order_Date,Quantity,Unit_Price,Discount_Percent,...,Net_Sales,Profit,Payment_Method,Customer_Type,Sales_Channel,Order_Status,Return_Status,Customer_Feedback,Rating,Year
0,ORD10000,CUST1125,Mary Wanjiku,Thika,Desktop,Computers,2026-10-17,2.0,1500.0,-5.0,...,3150.0,-12850.0,NaN,NaN,Physical Store,Completed,Yes,Neutral,2.0,NaN
1,ORD10001,CUST1359,David Kariuki,Eldoret,Printer,Office Equipment,2026-09-09,1.0,25000.0,-5.0,...,26250.0,-33750.0,NaN,Institution,Physical Store,Cancelled,no,Dissatisfied,3.0,2025.0
2,ORD10002,CUST1049,Peter Otieno,Kisumu,UPS,Networking,2025-08-09,20.0,5000.0,0.0,...,100000.0,-260000.0,Cash,NaN,Physical Store,NaN,Yes,Dissatisfied,7.0,NaN
3,ORD10003,CUST1023,NaN,Nakuru,Router,Computers,2026-09-26,20.0,25000.0,-5.0,...,525000.0,509000.0,Card,Individual,NaN,Pending,no,Dissatisfied,2.0,2026.0
4,ORD10004,CUST1331,John Mwangi,Thika,Projector,Accessories,2025-12-30,5.0,50000.0,-5.0,...,262500.0,-37500.0,Card,NaN,NaN,Pending,NaN,Neutral,NaN,2026.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,ORD11410,CUST1119,David Kariuki,Nyeri,Projector,Computers,2026-08-12,10.0,50000.0,15.0,...,425000.0,395000.0,Mobile Money,Business,Physical Store,Pending,no,NaN,3.0,2025.0
1996,ORD11515,CUST1230,Amina Hassan,Westlands,UPS,Accessories,2026-07-21,5.0,-500.0,NaN,...,NaN,NaN,Bank Transfer,Institution,Online,Pending,YES,Satisfied,5.0,2026.0
1997,ORD10809,CUST1080,NaN,Kisumu,Laptop,Accessories,2026-06-05,20.0,25000.0,NaN,...,NaN,NaN,Card,Individual,NaN,Pending,no,Neutral,3.0,2025.0
1998,ORD10830,CUST1304,Peter Otieno,Thika,Desktop,Accessories,2025-11-02,5.0,85000.0,10.0,...,382500.0,207500.0,Cash,Institution,NaN,Completed,No,NaN,1.0,2025.0
1999,ORD10859,CUST1318,Peter Otieno,Eldoret,Mouse,Computers,2026-06-18,1.0,25000.0,10.0,...,22500.0,14500.0,Mobile Money,Individual,Online,NaN,no,Dissatisfied,4.0,2026.0

In [31]:
df.isnull().any(axis=1).sum()

np.int64(1899)

In [32]:
df.isnull().any().sum()

np.int64(16)

In [33]:
df.columns[
    df.isnull().any()
    ]

Index(['Customer_Name', 'Quantity', 'Unit_Price', 'Discount_Percent',
       'Gross_Revenue', 'Cost', 'Net_Sales', 'Profit', 'Payment_Method',
       'Customer_Type', 'Sales_Channel', 'Order_Status', 'Return_Status',
       'Customer_Feedback', 'Rating', 'Year'],
      dtype='str')

In [35]:
list(
    df.columns[
        df.isnull().any()
        ]
)

['Customer_Name',
 'Quantity',
 'Unit_Price',
 'Discount_Percent',
 'Gross_Revenue',
 'Cost',
 'Net_Sales',
 'Profit',
 'Payment_Method',
 'Customer_Type',
 'Sales_Channel',
 'Order_Status',
 'Return_Status',
 'Customer_Feedback',
 'Rating',
 'Year']